MongoDB
AinisSitkauskas/Dienynas pull request #11
Opened 2019-10-03 17:21 UTC by AinisSitkauskas

2019-10-10 19:20 UTC, mykolasjarasiunas requested changes

2019-10-10 19:20 UTC, mykolasjarasiunas commented on src/Controller/LoginController.php
> +     * @var PaswordHasher
Buvo gerai :smile:

2019-10-10 19:20 UTC, mykolasjarasiunas commented on src/Database.php
> +    function __construct();
Konstruktorių paprastai nededam į interface aprašus

2019-10-10 19:20 UTC, mykolasjarasiunas commented on src/Model/MysqlDB.php
> +        include_once("parameters.php");
Kitų failų includinimas (taip pat ir pvz skaitymas iš failo) nėra gera operacija konstruktoriui. Tuo labiau su hardcoded filename. žymiai geriau reikalingą info perduoti parametrais.

2019-10-10 19:20 UTC, mykolasjarasiunas commented on src/Database.php
> +    public function getUser($user);
O tau keistai neatrodo, kai prašai iš f-jos vartotojo, nors pats jį paduodi parametru? Panašių funkcijų būna, bet jos dažniausiai užvadinamos pvz fillUser($user) ir kviečiamos kai iš anksto žinome kad bus kuo tą user užpildyti. Mūsų atveju geriau būtų turėti public function getUser($username, $password) kuri jau grąžintų užpildytą user objektą, arba null, jei tokio vartotojo nerado.  
Bendram spratimui į ateitį: jeigu kadanors teks išsaugoti atnaujintą user info būtų logiška apsirašyti funkciją saveUser($user) ir čia user objektas kaip parametras jau būtų ok

2019-10-29 07:14 UTC, mykolasjarasiunas requested changes

2019-10-29 07:14 UTC, mykolasjarasiunas commented on src/Controller/LoginController.php
> +     * @var PasswordHasher
Kam tas tarpas eilutės gale? Paieškok, turėtų būti galima savo IDE (NetBeans?) susikonfigūruoti, kad failo išsaugojimo metu pašalintų trailing spaces automatiškai

2019-10-29 07:14 UTC, mykolasjarasiunas commented on src/Database.php
> +    public function getUser($userName);
Tik pastaba į ateitį: Pasidaro situacijų kad vartotoją iš DB reikia ištraukti ne tik pagal vartotojo vardą, bet ir pvz pagal pavardę, ID, asmens kodą ar dar ką nors. Tuomet paprastai atsiranda metodai getUserByUsername, getUserBySurname, getUserByID, etc.

2019-10-29 07:14 UTC, mykolasjarasiunas commented on src/Database.php
> +    public function userExist($user);
šiai f-jai User tipo argumentas retai kada būna logiškas. žymiai geriau paduoti tiesiogiai paieškos kriterijų ar jų masyvą kaip argumentą "...Exists" funkcijai. Jei paduodi User objektą, kažkaip ir semantiškai nelabai logiška klausti ar egzistuoja vartotojas, kai tu jau jį padavei kaip argumentą :)

Tiesa su "...Exists" f-jų namingu, kai naudoji skirtingu paieškos kriterijus nebėra taip lengva. Teko matyti ir userWithUsernameExists, userWithIDExists, bet dažniausiai visgi naudoja pvz getUserByID ir jeigu ji grąžina null - reiškia not exists

2019-10-29 07:14 UTC, mykolasjarasiunas commented on src/Database.php
> +    public function registerUser($user);
Pagal failo pavadinimą kontekstas yra DB. DB nelabai aišku kas per sąvoka yra "Priregistruok vartotoją". DB kontekste žymiai geriau skaitosi "Išsaugok vartotoją". 
žiūrint į kitas interface f-jas galima tokią negrieštą paralelę įžvelgt:
getUser ~ sql SELECT
userExists ~ sql COUNT > 0
saveUser ~ sql INSERT
deleteUser ~ sql DELETE
registerUser ~ sql ??

2019-11-06 15:22 UTC, AinisSitkauskas commented on src/Controller/LoginController.php
> +     * @var PasswordHasher
Radau, kad NetBeans panaikintų trailing white spaces, pažiūrėsim ar tikrai tai veikia, tiesa, dabar jau perėjau ant PHP storm, kadangi gavau licenziją ir tai geriausias įrankis, nors kaip tu ir buvai sakęs, kad Net Beans nedaug nusileidžia PHP stromui. PS. Šį paskutinį commitą, dar padarysiu su NetBeans

2019-11-06 16:03 UTC, AinisSitkauskas commented on src/Database.php
> +    public function registerUser($user);
Ties šiuo komentaru man kyla klausimų (Visi kiti kaip ir aiškūs ir suprantami). Ar tikrai _saveUser_ čia būtų geriausias pasirinkimas ? Galbūt netgi geriau, tokiu atveju, būtų funkcija _insertUser_  ? Įdomu, kokie įprastai funkcijų pavadinimu tokiu atveju būna, nes tas saveUser, dabar tik pusiau man limpa :D . Kodą pataisysiu pagal rekomendacijas, bet įdomu ką atsakysi į klausimus.

2019-11-10 09:49 UTC, mykolasjarasiunas commented on src/Controller/LoginController.php
> +     * @var PasswordHasher
Panašu kad veikia. Ir ne tik trailing spaces, bet ir kitus "spacing" issues dabar pataisei. Liuks. Naudok tokį IDE kuris tau patogiausias/naudingiausis. Man tikrai jokio skirtumo :smiley:

2019-11-10 09:59 UTC, mykolasjarasiunas commented on src/Database.php
> +    public function registerUser($user);
Didelio skirtumo tarp save ir insert nematau. Labiau gal tavo paties (ar tavo komandos arba net projekto prie kurio tenka dirbti) pasirinkimas. Svarbu kad tavo projekte būtų aišku, kad iškvietus vat šią funkciją vartotojas atsiras duombazėje. Tiesa su insert - labiau aišku kad atsiras naujas įrašas db. Save tuo tarpu man labiau atitiktų Insert or Update (mysql turi tokią konstrukciją: http://www.mysqltutorial.org/mysql-insert-or-update-on-duplicate-key-update/). Tai jeigu turint omeny šį skirtumą - labiausiai svarbu ko tavo projektui reikia. Jeigu visada reiks insert or update - tada gal geriau turėt vieną f-ją ir naudot save pavadinimą (nors yra tekę matyti kad save=insert; bet vėlgi "teko matyti" != "ten buvo gerai padaryta" :smile: ). 
FYI: tiek mysql tiek mongo turi insert sakinius. Bet ne visos DB tuo pasižymi. Pvz yra tokia DynamoDB, kur jau yra tik Put/Update statementai (kiek pačiam įdomu - gali žvilgtelt: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html)

2019-11-10 10:06 UTC, mykolasjarasiunas approved these changes
Tai va manau jau ir padarei kažką panašaus, kur buvo reikalavimas "visa DB logika viename faile" (pas tave dabar 2 failai src/Model/MongoDB.php ir src/Model/MysqlDB.php nes papildomai padarėm kad tiktų 2 DB). Tai čia esmė, kad likusi tavo projekto dalis su DB bendrauja per vieną iš šių failų ir jeigu kada rekės pakeisti DB į kitokią - pakeitimai bus reikalingi tik tame faile (arba tiesiog confige nurodysi kad reikia naudoti kitą failą), o visos likusios projekto logikos keisti/perrašinėti nereikės

2019-11-10 10:06 UTC, merged